project:
  type: website
  output-dir: docs

website:
  title: "spatial-statistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - text: Geostatistics
        menu:
          - text: Overview
            href: geostatistics/index.qmd
          - text: Temperature
            href: geostatistics/temp.qmd
          - text: Ozone
            href: geostatistics/ozone.qmd
          - text: Spatio-temporal
            href: geostatistics/spacetime.qmd
          - text: Functional Data Analysis
            href: geostatistics/fd.qmd
            
      - href: arealdata/datos_area.qmd
        text: Areal Data
        
      - about.qmd
      
  page-footer: 
    left: "Copyright 2025, Camilo GÃ³mez" 
    right: 
      - icon: github
        href: https://github.com/camiloogmz
      - icon: linkedin 
        href: https://www.linkedin.com/in/camiloogmz/

format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    toc: true



